plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/chelsey/Downloads/Brilliant-Learning/artifacts/learning-platform/artifacts/learning-platform/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/chelsey/Downloads/Brilliant-Learning/artifacts/learning-platform"
command = "pnpm --filter @workspace/learning-platform... run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]